version: '3.7'
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - ./server:/app
        expose:
            - 3001
        ports:
            - 3001:3001
        environment:
            - PORT=3001
        stdin_open: true
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - ./client:/app
        expose:
            - 3000
        ports:
            - 3000:3000
        environment:
            - PORT=3000
        links:
            - server
        stdin_open: true
